root: true

env:
  browser: true
  es2021: true
  'vue/setup-compiler-macros': true
  'vitest-globals/env': true

parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module

plugins:
  - vue
  - '@typescript-eslint'
  - vitest

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/base'
  - 'plugin:vue/vue3-essential'
  - 'plugin:vue/vue3-recommended'
  - 'plugin:vue/vue3-strongly-recommended'
  - 'plugin:vitest/recommended'
  - 'plugin:vitest-globals/recommended'
  - 'prettier'

rules:
  'no-unused-vars': 'off'
  'vitest/consistent-test-it':
    - 'error'
    - 'fn': 'test'
  'vitest/require-top-level-describe':
    - error
  'vue/component-tags-order':
    - 'error'
    - 'order':
        - 'script'
        - 'template'
        - 'style'
  '@typescript-eslint/no-explicit-any': 0
